### ISSUE TITLE
Remodel bug

### ISSUE THREAD

**Issue by barbazul** [barbazul/dominion-AIrena#1]
Relevant portion of the log

```
cleanup phase
(SillyAI shuffles.)
SillyAI draws 5 cards: Cellar,Copper,Remodel,Cellar,Duchy.
[...]
=== SillyAI's turn 15
start phase
action phase
SillyAI plays Cellar.
SillyAI discards Duchy.
SillyAI discards Copper.
SillyAI draws 2 cards: Estate,Throne Room.  <- Current hand: Cellar,Remodel,Estate,Throne Room
SillyAI plays Throne Room.
SillyAI plays Cellar.
SillyAI discards Estate.
SillyAI draws 1 cards: Throne Room.   <- Current hand: Remodel,Throne Room
...plays Cellar again.
SillyAI draws 0 cards: .
SillyAI plays Throne Room.
SillyAI plays Remodel.    <- At this point the hand is empty
(crash)
```

**Comment by barbazul** [comment]
Stack trace:

```
TypeError: Cannot read property 'trash' of null
at Remodel.playEffect (file:///C:/wamp64/www/dominion/src/cards/remodel.js:48:41)
at Remodel.onPlay (file:///C:/wamp64/www/dominion/src/cards/card.js:103:10)
at State.resolveAction (file:///C:/wamp64/www/dominion/src/game/state.js:220:12)
at ThroneRoom.playEffect (file:///C:/wamp64/www/dominion/src/cards/throneRoom.js:37:13)
at ThroneRoom.onPlay (file:///C:/wamp64/www/dominion/src/cards/card.js:103:10)
at State.resolveAction (file:///C:/wamp64/www/dominion/src/game/state.js:220:12)
at ThroneRoom.playEffect (file:///C:/wamp64/www/dominion/src/cards/throneRoom.js:37:13)
at ThroneRoom.onPlay (file:///C:/wamp64/www/dominion/src/cards/card.js:103:10)
at State.resolveAction (file:///C:/wamp64/www/dominion/src/game/state.js:220:12)
at State.playAction (file:///C:/wamp64/www/dominion/src/game/state.js:208:10)
```

**Comment by barbazul** [comment]
Same bug with Mine

```
file:///C:/wamp64/www/dominion/src/cards/mine.js:1
TypeError: Cannot read property 'trash' of null
    at Mine.playEffect (file:///C:/wamp64/www/dominion/src/cards/mine.js:23:41)
    at Mine.onPlay (file:///C:/wamp64/www/dominion/src/cards/card.js:103:10)
    at State.resolveAction (file:///C:/wamp64/www/dominion/src/game/state.js:220:12)
    at State.playAction (file:///C:/wamp64/www/dominion/src/game/state.js:208:10)
    at State.doActionPhase (file:///C:/wamp64/www/dominion/src/game/state.js:638:12)
    at State.doPhase (file:///C:/wamp64/www/dominion/src/game/state.js:591:14)
    at Object.<anonymous> (file:///C:/wamp64/www/dominion/run.js:49:9)
    at Generator.next (<anonymous>)
```

**Comment by barbazul** [comment]
Fixed!
